### PR TITLE
React Rails one app setup

### PR DESCRIPTION
**Pull request by pushkar1995**
In this branch, I implemented the following:

Created a new Rails app called 'hello-rails-react'.
Used the command rails new -j web pack my_new_rails_app.
Verify that the jsbundling-rails gem is added to your Gemfile.
Installed needed node dependencies.
Created a babel.config.js in the root folder of my project.
Updated webpack.config.js to include the babel-loader.
Ensured that the project has a Postgres database set up.
Created a table for storing messages and created 5 different greetings.
Created an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
Created a static view that will be the root of your app.
Created the App component with react-router and rendered it in my static view.
Created the Greeting component that will display a greeting. Set it up as a route in your App component.
Created a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
Display the random greeting in my Greeting component.

### CODE REVIEW

**Review by mukhammadrizooff — COMMENTED** [review]
Hi @pushkar1995, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that `linters` should be installed and passed 🙏🏼 
image



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by pushkar1995** [comment]
@mukhammadrizooff Thankyou for the review.I just fixed the linters and submitted again.

**Comment by pushkar1995** [comment]
@mukhammadrizooff But in my Dashboard, it's still showing Review Pending. Please help me to resolve this.

**Review by mukhammadrizooff — APPROVED** [review]
Hi @pushkar1995, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

 

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pushkar1995** [comment]
@mukhammadrizooff Thank you so much for the review and the approval of PR.

**Pull request merged**
